### PR TITLE
.NET Standard Support

### PR DESCRIPTION
**Pull request by NathanNZ**
Hey there,

I've added .NET Standard support to help us add this functionality into Jackett, this does require VS2017 to build - but shouldn't effect existing .NET consumers at all as the nuget package that automatically gets generated will support both .NET 4 and .NET Standard 2 👍 

Let me know if you have any questions/feedback/suggestions! 

For Reference:
https://github.com/Jackett/Jackett/pull/2058
https://github.com/postworthy/SocksWebProxy/pull/5

### CODE REVIEW

**Comment by lloydsparkes** [comment]
Hi,

Thanks for this, its something I've been meaning to do. I will have a play around this week, but I don't see any issues

Thanks,

**Comment by lloydsparkes** [comment]
Done, and Packaged

**Comment by NathanNZ** [comment]
Awesome - looking forward to seeing it up on the public nuget repository!

**Comment by lloydsparkes** [comment]
Just noticed, I need to tweak the package name, it uploaded as a different package id onto Nuget. 

I'll correct it this evening

**Comment by lloydsparkes** [comment]
Fixed and public

https://www.nuget.org/packages/DotNet4.SocksProxy/1.4.0

**Pull request merged**
